# Generated by Django 2.2 on 2019-09-12 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('account_created_on', models.DateTimeField(default=datetime.datetime(2019, 9, 12, 10, 41, 10, 784443))),
            ],
        ),
    ]
