# Generated by Django 2.2 on 2019-09-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Que',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('a', models.TextField()),
                ('aw', models.PositiveIntegerField()),
                ('b', models.TextField()),
                ('bw', models.PositiveIntegerField()),
                ('c', models.TextField()),
                ('cw', models.PositiveIntegerField()),
                ('d', models.TextField()),
                ('dw', models.PositiveIntegerField()),
                ('domain', models.CharField(max_length=20)),
            ],
        ),
    ]
