# Generated by Django 2.2 on 2019-09-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_que'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Que',
            new_name='Quest',
        ),
    ]
