# Generated by Django 2.2 on 2019-09-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190915_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='qid',
            field=models.CharField(max_length=5),
        ),
    ]
