# Generated by Django 2.2 on 2019-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190916_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='qid',
        ),
        migrations.AlterField(
            model_name='quest',
            name='domain',
            field=models.CharField(choices=[('co', 'Confidence'), ('fi', 'Fitness'), ('ac', 'Acadamics'), ('pd', 'Personality Development'), ('mi', 'Miscellenous')], default='mi', max_length=2),
        ),
    ]
